### ISSUE TITLE
Query doesn't take into account versioned profiles in auto mode

### ISSUE THREAD

**Issue by realjordanna** [GoogleCloudPlatform/bq-pii-classifier#115]
https://github.com/GoogleCloudPlatform/bq-pii-classifier/blob/16c7f9b3fbc59d3687abcdb763d9fdc1c51e93b1/services/library/src/main/java/com/google/cloud/pso/bq_pii_classifier/services/scan/AutoDlpResultsScannerImpl.java#L100C1-L101C1

The bigquery table containing profiles will contain multiple profiles whenever the profile is updated. This fails to pick the most recent one and instead merges old data together with new.

if you query the "table" + _latest_v1 table, which is a view we provide customers we offer the most recent one, then you won't need distinct in the query and won't pull stale profiles.

**Comment by kwadie** [comment]
Thanks @realjordanna for reporting this. The latest_v1 is the one being used (passed via Terraform). I renamed the variable to avoid confusion. This is fixed in v1.0.7.
