### ISSUE TITLE
listChildren javadoc is wrong

### ISSUE THREAD

**Issue by realjordanna** [GoogleCloudPlatform/bq-pii-classifier#116]
https://github.com/GoogleCloudPlatform/bq-pii-classifier/blob/16c7f9b3fbc59d3687abcdb763d9fdc1c51e93b1/services/library/src/main/java/com/google/cloud/pso/bq_pii_classifier/services/scan/AutoDlpResultsScannerImpl.java#L97C1-L98C1

This lists profiles, not jobs. javadoc is wrong.

**Comment by kwadie** [comment]
Thanks @realjordanna for reporting this. This is fixed in v1.0.7.
