### ISSUE TITLE
Broken link in common-terraform-2-variables.md

### ISSUE THREAD

**Issue by sergiospa** [GoogleCloudPlatform/bq-pii-classifier#163]
Hi!

First of all, thank you for providing this great project.

I wanted to let you know that there is a broken link here that I would really like to see: 
https://github.com/GoogleCloudPlatform/bq-pii-classifier/blob/fix/update_broken_links_data_services/docs/common-terraform-2-variables.md

The link in particular should point to the example configuration file _example-discovery-service-mode_:
https://github.com/GoogleCloudPlatform/bq-pii-classifier/blob/fix/update_broken_links_data_services/docs/terraform/example-discovery-service-mode.tfvars

This file would really help understanding and implementing the project. Could you please fix the link or provide an updated one?

Thank you in advance for your assistance and for your hard work on this project.

Best regards,
Sergio.

**Comment by kwadie** [comment]
Thanks @sergiospa for reporting this. I fixed it in [v1.0.8](https://github.com/GoogleCloudPlatform/bq-pii-classifier/tree/v1.0.8)

**Comment by sergiospa** [comment]
Thanks a lot!!
